export * from './about-us'
export * from './articles'
export * from './home'
export * from './posts'
export * from './projects'
export * from './stack'
export * from './qr-pan-de-jamon'
export * from './instructions'
